duration:
    pomodoro: 25
    break: 5
commands:
    pomodoro:
        start:
            - terminal-notifier -message "Pomodoro started!"
            - osascript -e 'tell application "Spotify" to play';
        stop:
            - osascript -e 'tell application "Spotify" to pause';
        end:
            - terminal-notifier -message "Pomodoro ended!"
            - osascript -e 'tell application "Spotify" to pause';
    break:
        start:
            - terminal-notifier -message "Break started!"
        end:
            - terminal-notifier -message "Break ended!"
