duration:
    pomodoro: 25
    break: 5
event:
    pomodoro:
        start:
            - terminal-notifier -message "Inizio pomodoro"
         end:
            - terminal-notifier -message "Fine pomodoro"
    break:
        start:
            - terminal-notifier -message "Inizio pausa :)"
        end:
            - terminal-notifier -message "Fine pausaaaaaa"
