duration:
    pomodoro: 25
    break: 1
commands:
    pomodoro:
        start:
            - terminal-notifier -message "Inizio pomodoro"
            - osascript -e 'tell application "Spotify" to play';
        end:
            - terminal-notifier -message "Fine pomodoro"
            - osascript -e 'tell application "Spotify" to pause';
    break:
        start:
            - terminal-notifier -message "Inizio pausa :)"
        end:
            - terminal-notifier -message "Fine pausaaaaaa"
