default:
    duration: 25
    start:
        - terminal-notifier -message "Pomodoro started!"
        - osascript -e 'tell application "Spotify" to play';
    stop:
        - terminal-notifier -message "Pomodoro stopped!"
        - osascript -e 'tell application "Spotify" to pause';
    end:
        - terminal-notifier -message "Pomodoro ended!"
        - osascript -e 'tell application "Spotify" to pause';
break:
    duration: 5
    start:
        - terminal-notifier -message "Break started!"
    stop:
        - terminal-notifier -message "Break stopped!"
    end:
        - terminal-notifier -message "Break ended!"
longbreak:
    duration: 15
    start:
        - terminal-notifier -message "Long break started!"
    stop:
        - terminal-notifier -message "Long break stopped!"
    end:
        - terminal-notifier -message "Long break ended!"
